name: vraxion-deployment

on:
  push:
    branches: ["master"]
  pull_request:
       branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build vraxion
        run: make build
      - name: Test vraxion
        run: make test
      - uses: jamescurtin/isort-action@master
      - name: Run isort
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"